config/routes.rb
ElasticMongo::Application.routes.draw do
  resources :searches

  resources :elastic_slacklines

  resources :jumping_mongos do
    collection do
      post 'search'
    end
  end

  root :to => 'jumping_mongos#search'

end

app/models/elastic_slackline.rb
class ElasticSlackline
  include Mongoid::Document

  field :name, type: String
  field :weight, type: Integer
  field :elasticity, type: Float

  attr_accessible :name, :weight, :elasticity

  has_many :jumping_mongos

end

app/models/jumping_mongo.rb
class JumpingMongo
  include Mongoid::Document
  include Tire::Model::Search

  belongs_to :elastic_slackline

  field :name, type: String
  field :url, type: String

  attr_accessible :name, :url, :elastic_slackline

  after_save :index

  tire do
    mapping :analyzer => 'snowball' do
      indexes :name, :type => 'string'
    end
  end

  def to_indexed_json
    {
        :id => id,
        :name => name,
        :slackline => elastic_slackline ? elastic_slackline.name : ""
    }.to_json
  end

  def index
    update_index
  end


end

app/models/search.rb
class Search

  include Mongoid::Document

  attr_accessor :query
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/elastic_slacklines_controller.rb
class ElasticSlacklinesController < ApplicationController
  # GET /elastic_slacklines
  # GET /elastic_slacklines.json
  def index
    @elastic_slacklines = ElasticSlackline.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @elastic_slacklines }
    end
  end

  # GET /elastic_slacklines/1
  # GET /elastic_slacklines/1.json
  def show
    @elastic_slackline = ElasticSlackline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @elastic_slackline }
    end
  end

  # GET /elastic_slacklines/new
  # GET /elastic_slacklines/new.json
  def new
    @elastic_slackline = ElasticSlackline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @elastic_slackline }
    end
  end

  # GET /elastic_slacklines/1/edit
  def edit
    @elastic_slackline = ElasticSlackline.find(params[:id])
  end

  # POST /elastic_slacklines
  # POST /elastic_slacklines.json
  def create
    @elastic_slackline = ElasticSlackline.new(params[:elastic_slackline])

    respond_to do |format|
      if @elastic_slackline.save
        format.html { redirect_to @elastic_slackline, notice: 'Elastic slackline was successfully created.' }
        format.json { render json: @elastic_slackline, status: :created, location: @elastic_slackline }
      else
        format.html { render action: "new" }
        format.json { render json: @elastic_slackline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /elastic_slacklines/1
  # PUT /elastic_slacklines/1.json
  def update
    @elastic_slackline = ElasticSlackline.find(params[:id])

    respond_to do |format|
      if @elastic_slackline.update_attributes(params[:elastic_slackline])
        format.html { redirect_to @elastic_slackline, notice: 'Elastic slackline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @elastic_slackline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elastic_slacklines/1
  # DELETE /elastic_slacklines/1.json
  def destroy
    @elastic_slackline = ElasticSlackline.find(params[:id])
    @elastic_slackline.destroy

    respond_to do |format|
      format.html { redirect_to elastic_slacklines_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/jumping_mongos_controller.rb
class JumpingMongosController < ApplicationController

  def search
    @search = Search.new(params[:search])
    if @search.query.present?
      @jumping_mongos = JumpingMongo.search @search.query, :per_page => 50, :load => true
    else
      @jumping_mongos = JumpingMongo.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @elastic_slacklines }
    end
  end

  # GET /jumping_mongos/1
  # GET /jumping_mongos/1.json
  def show
    @jumping_mongo = JumpingMongo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @jumping_mongo }
    end
  end

  # GET /jumping_mongos/new
  # GET /jumping_mongos/new.json
  def new
    @jumping_mongo = JumpingMongo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @jumping_mongo }
    end
  end

  # GET /jumping_mongos/1/edit
  def edit
    @jumping_mongo = JumpingMongo.find(params[:id])
  end

  # POST /jumping_mongos
  # POST /jumping_mongos.json
  def create
    @jumping_mongo = JumpingMongo.new(params[:jumping_mongo])

    respond_to do |format|
      if @jumping_mongo.save
        format.html { redirect_to @jumping_mongo, notice: 'Jumping mongo was successfully created.' }
        format.json { render json: @jumping_mongo, status: :created, location: @jumping_mongo }
      else
        format.html { render action: "new" }
        format.json { render json: @jumping_mongo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jumping_mongos/1
  # PUT /jumping_mongos/1.json
  def update
    @jumping_mongo = JumpingMongo.find(params[:id])

    respond_to do |format|
      if @jumping_mongo.update_attributes(params[:jumping_mongo])
        format.html { redirect_to @jumping_mongo, notice: 'Jumping mongo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @jumping_mongo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jumping_mongos/1
  # DELETE /jumping_mongos/1.json
  def destroy
    @jumping_mongo = JumpingMongo.find(params[:id])
    @jumping_mongo.destroy

    respond_to do |format|
      format.html { redirect_to search_jumping_mongos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elastic_slacklines_helper.rb
module ElasticSlacklinesHelper
end

app/helpers/jumping_mongos_helper.rb
module JumpingMongosHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/elastic_slacklines/_form.html.haml
= form_for @elastic_slackline do |f|
  - if @elastic_slackline.errors.any?
    #error_explanation
      %h2= "#{pluralize(@elastic_slackline.errors.count, "error")} prohibited this elastic_slackline from being saved:"
      %ul
        - @elastic_slackline.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :weight
    = f.number_field :weight
  .field
    = f.label :elasticity
    = f.text_field :elasticity
  .actions
    = f.submit 'Save'

app/views/elastic_slacklines/edit.html.haml
%h1 Editing elastic_slackline

= render 'form'

= link_to 'Show', @elastic_slackline
\|
= link_to 'Back', elastic_slacklines_path

app/views/elastic_slacklines/index.html.haml
%h1 Listing elastic_slacklines


%table
  %tr
    %th Name
    %th Weight
    %th Elasticity
    %th
    %th
    %th

  - @elastic_slacklines.each do |elastic_slackline|
    %tr
      %td= elastic_slackline.name
      %td= elastic_slackline.weight
      %td= elastic_slackline.elasticity
      %td= link_to 'Show', elastic_slackline
      %td= link_to 'Edit', edit_elastic_slackline_path(elastic_slackline)
      %td= link_to 'Destroy', elastic_slackline, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Elastic slackline', new_elastic_slackline_path

app/views/elastic_slacklines/new.html.haml
%h1 New elastic_slackline

= render 'form'

= link_to 'Back', elastic_slacklines_path

app/views/elastic_slacklines/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @elastic_slackline.name
%p
  %b Weight:
  = @elastic_slackline.weight
%p
  %b Elasticity:
  = @elastic_slackline.elasticity

= link_to 'Edit', edit_elastic_slackline_path(@elastic_slackline)
\|
= link_to 'Back', elastic_slacklines_path

- if false
  %h2 JumpingMongos
  - @elastic_slackline.jumping_mongos.each do |jm|
    = render jm

app/views/jumping_mongos/_form.html.haml
= form_for @jumping_mongo do |f|
  - if @jumping_mongo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@jumping_mongo.errors.count, "error")} prohibited this jumping_mongo from being saved:"
      %ul
        - @jumping_mongo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :slackline_id
    = f.text_field :slackline_id
  .actions
    = f.submit 'Save'

app/views/jumping_mongos/edit.html.haml
%h1 Editing jumping_mongo

= render 'form'

= link_to 'Show', @jumping_mongo
\|
= link_to 'Back', jumping_mongos_path

app/views/jumping_mongos/new.html.haml
%h1 New jumping_mongo

= render 'form'

= link_to 'Back', jumping_mongos_path

app/views/jumping_mongos/search.html.haml
= simple_form_for @search, :url => search_jumping_mongos_url, :method => :post do |f|
  = f.input :query, :class => 'string', :input_html => { :cols => 50, :rows => 3 }

  = f.submit 'search'

%p= "Found: #{@jumping_mongos.total}" unless @jumping_mongos.is_a? Mongoid::Criteria
%table
  %tr
    %th Name
    %th Slackline
    %th
    %th
    %th

  - @jumping_mongos.each do |jumping_mongo|
    %tr
      %td= jumping_mongo.name
      %td= jumping_mongo.elastic_slackline.name if jumping_mongo.elastic_slackline
      %td= link_to jumping_mongo.url, jumping_mongo.url
      %td= link_to 'Show', jumping_mongo
      %td= link_to 'Edit', edit_jumping_mongo_path(jumping_mongo)
      %td= link_to 'Destroy', jumping_mongo, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Jumping mongo', new_jumping_mongo_path

app/views/jumping_mongos/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @jumping_mongo.name
%p
  %b Slackline:

= link_to 'Edit', edit_jumping_mongo_path(@jumping_mongo)
\|
= link_to 'Back', jumping_mongos_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElasticMongo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>